INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Arme tranchante');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Arme perforante');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Arme contondante');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Arme ___________');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Arme Arc');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Arme Fronde');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Arme de jet');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Athléthisme');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Bouclier');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Cond. Attelage');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Endurance');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Equitation');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Esquive');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Grimper');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Natation');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Pugilat');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Souplesse');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '1', 'Vol à la tire');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Agriculture');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Alchimie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Artisanat Forge');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Artisanat Charpentier');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Artisanat');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Epos animaux');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Epos plantes');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Epos géographie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Epos mythologie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Epos créatures fabuleuses');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Epos Us & coutumes');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Gestion Patrimoine');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Ingénieurie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Lire/écrire grec');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Lire/écrire barbare');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Lire/écrire Aegyptien');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Médecine');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Navigation');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Occultisme');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Pièges');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Résistance');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Stratégie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Survie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '2', 'Théologie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Arts lyriques');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Commandement');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Comédie/Danse');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Diplomatie');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Discrétion');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Divination');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Dressage');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Evaluation');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Fouille');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Intimidation');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Marchandage');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Parler grec');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Parler aegyptien');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Parler barbare');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Perception');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Persuasion');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Pistage');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Politique');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Séducation');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Sensibilité');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Vigilance');
INSERT INTO `talent` (`ID_TALENT`, `ID_CAT`, `NOM`) VALUES (NULL, '3', 'Réseau');
INSERT INTO `categorie` (`ID_CAT`, `NOM`) VALUES (NULL, 'SOMA');
INSERT INTO `categorie` (`ID_CAT`, `NOM`) VALUES (NULL, 'SOPHOS');
INSERT INTO `categorie` (`ID_CAT`, `NOM`) VALUES (NULL, 'SYMBIOSE');